config/routes.rb
Rails.application.routes.draw do
  get                '/',    to: 'home#index', as: :root
  resources :signup, only: [:new, :create]
  get            'login',    to: 'sessions#new'
  post           'login',    to: 'sessions#create'
  delete        'logout',    to: 'sessions#delete'
  resources :posts, expect: [:index]
  resources :comments, only: [:show, :create, :update, :destroy]
  namespace :mypage do
    resources :user, only: [:show]
  end
  namespace :setting do 
    resources :user, only: [:show, :update]
  end
  get     'withdraw/:id',    to: 'withdraw#show', as: :show_withdraw
  delete  'withdraw/:id',    to: 'withdraw#delete', as: :delete_withdraw
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
  validates :name, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  
  has_many :comments, dependent: :destroy
  has_one_attached :post_image

  validates :title, presence: true
  validates :article, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :posts, dependent: :destroy
  has_one_attached :user_image

  validates :name, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_confirmation, only:[:update, :destroy]

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:comment][:post_id])
    new_comments = @post.comments.build(comment_params)
    if new_comments.save
      redirect_back(fallback_location: root_path, notice: '投稿に成功しました。')
    else
      render 'posts/show', alert: '編集に失敗しました。'
    end
  end

  def update
    comment = Comment.find(params[:id])
    if comment.update_attributes(comment_params)
      redirect_back(fallback_location: root_path, notice: '編集に成功しました。')
    else
      redirect_back(fallback_location: root_path, alert: '編集に失敗しました。')
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_back(fallback_location: root_path, notice: '削除に成功しました。')
    else
      redirect_back(fallback_location: root_path, alert: '削除に失敗しました。')
    end
  end

private
  def comment_params
    params.require(:comment).permit(:name, :comment)
  end

  def user_confirmation
    @comment = Comment.find(params[:id])
    unless current_user.id == @comment.post.user_id
      flash[:alert] = "コメント編集は記事の投稿者のみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/mypage/user_controller.rb
class Mypage::UserController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_confirmation, only: [:edit, :update, :destroy]

  def new 
    @post = Post.new
  end

  def create
    current_user.present? ? @post = current_user.posts.build(post_params) : @post = Post.new(post_params)
    if @post.save
      flash[:notice] = '投稿に成功しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '投稿に失敗しました。'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = '更新に成功しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '更新に失敗しました。'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy!
      flash[:notice] = '削除しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '削除に失敗しました。'
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :article, :post_image)
  end

  def user_confirmation
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      flash[:alert] = "記事編集は投稿者のみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password]) && withdraw_user(user)
      log_in user
      redirect_to "/mypage/user/#{user.id}"
    else
      flash[:alert] = '正しいメールアドレス、パスワードを入力してください。'
      redirect_back(fallback_location: root_path)
    end
  end

  def delete
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/setting/user_controller.rb
require'date'

class Setting::UserController < ApplicationController
  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    @user.birthday = birthday_join
    if @user.save
      redirect_back(fallback_location: root_path, notice: '編集に成功しました。')
    else
      render controller: :setting, action: :show, alert: '編集に失敗しました。'
    end
  end

  private

  def user_params
    params.require(:user).permit(:blog_name, :profile, :birthday, :user_image)
  end

  def birthday_join
    date = params[:user]
    Time.zone.local(date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i)
  end
end

app/controllers/setting_controller.rb
require'date'

class SettingController < ApplicationController
  include Common

  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    @user.birthday = birthday_join
    if @user.save
      redirect_back(fallback_location: root_path, notice: '編集に成功しました。')
    else
      render controller: :setting, action: :show, alert: '編集に失敗しました。'
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile, :birthday, :user_image)
  end

  def birthday_join
    date = params[:user]
    Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to "/mypage/user/#{@user.id}"
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:name, :blog_name, :email, :password, :password_confirmation)
  end
end

app/controllers/withdraw_controller.rb
class WithdrawController < ApplicationController
  before_action :user_confirmation, only: [:delete]

  def show
    @user = User.find(params[:id])
  end

  def delete
    @user = User.find(params[:id])
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
    flash[:notice] = '退会に成功しました。'
  end

  private
  def user_confirmation
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:alert] = "退会は登録ユーザーのみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user.id
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def withdraw_user(user)
    user.is_active
  end
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/mypage/user/show.html.erb
<article>
  <section class="top_area">
    <% if @user.blog_name.present? %>
      <h1><%= @user.blog_name %></h1>
    <% else %> 
      <h1>名無しのブログ</h1>
    <% end %>
    <% if flash[:error].present? %>
      <div class="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= image_tag '/title.jpg', class: "top_image" %>
  </section>
  <div class="container">
    <section class="main_area">
      <% if @user.posts.present? %>
        <%=render "layouts/posts", posts: @user.posts.order(created_at: :desc).page(params[:page]).per(5) %>
      <% else %>
        <p>まだ投稿されていません。</p>
      <% end %>
    </section>
    <section class="sidebar_area">
      <div class="btn_area">
        <%= link_to "投稿", new_post_path, class: "btn" %>
      </div>
      <% if @user.present? %>
        <div class="profile_thumbnail_area">
          <% if @user.user_image.attached? %>
            <%= image_tag @user.user_image, size: '300x300', class: "profile_thumbnail" %> 
          <% else %> 
            <%= image_tag "/no_image.png", class: "thumbnail_image" %>
          <% end%>
        </div>
        <div class="name_area">
          <%= @user.name %>
        </div>
        <% if @user.profile %> 
          <div class="profile_area">
            <%= @user.profile %>
          </div>
        <% end%>
        <% if @user.birthday %> 
          <div class="birthday_area">
            <%= l @user.birthday, format: :long %>
          </div>
        <% end%>
      <% end %>
    </section>
  </div>
</article>

app/views/posts/edit.html.erb
<article>
  <div class="container">
    <section class="main_area">
      <div class="input_area">
        <h1>記事修正</h1>
        <%= form_with model: @post, url: post_path do |f| %>
          <p>タイトル</p>
          <%= f.text_field :title, class: "title_area", size: "137*137" %>
          <p>記事</p>
          <%= f.text_area :article, class: "article_area", size: "136x50" %>
          <p>サムネイル</p>
          <% if @post.post_image.attached? %> 
            <%= image_tag @post.post_image, size: '300x300', class: "thumbnail_image" %> 
          <% end%>
          <label for="thumbnail_image" class="square_btn">画像選択
          <%= f.file_field :post_image, class: "ignore" %>
          </label><br>
          <%= f.submit "投稿", class: "btn" %>
        <% end %>
      </div>
    </section>
  </div>
</article>

app/views/posts/new.html.erb
<article>
  <div class="container">
    <section class="main_area">
      <div class="input_area">
        <h1>記事作成</h1>
        <%= form_with model: @post, url: posts_path do |f| %>
          <%= render 'layouts/error_form', model: @post %>
          <p>タイトル</p>
          <%= f.text_field :title, size: "137*137" %>
          <p>記事</p>
          <%= f.text_area :article, size: "136x50" %>
          <p>サムネイル画像</p>
          <label for="thumbnail_image" class="square_btn">画像選択
          <%= f.file_field :post_image, class: "ignore" %>
          </label><br>
          <%= f.submit "投稿", class: "btn" %>
        <% end %>
      </div>
    </section>
  </div>
</article>

app/views/posts/show.html.erb
<article>
  <div class="container">
    <section class="main_area">
      <section class="content_area">
        <% if flash[:comment_error].present? %>
          <div class="alert">
            <%= flash[:comment_error] %>
          </div>
        <% end %>
        <p><%= l @post.created_at, format: :long %></p>
        <h1><%= @post.title %></h1>
        <div class="thumbnail_area">
          <% if @post.post_image.attached? %> 
            <%= image_tag @post.post_image, size: '300x300', class: "thumbnail_image" %> 
          <% end%>
        </div>
        <p class="blog_area"><%= @post.article %></p>
      </section>
      <section class="comment_area">
        <% if @post.comments.present? %>
          <% @post.comments.order(created_at: :desc).each do |comment| %>
            <p><%= l comment.created_at, format: :long %></p>
            <p><%= comment.name %></p>
            <p><%= comment.comment %></p>
            <% if logged_in? && current_user?(@post.user_id) %>
              <div class="btn_area">
                <div class="comment_edit_buttom">
                  <button class="open_modal" data-id=<%=comment.id %>>編集</button>
                </div>
                <div class="overlay"></div>
                <div class="modalWindow" id=<%= comment.id%>>
                  <p>コメントの編集ができます。</p>
                  <%= form_with model: comment, method: :patch do |f| %>
                    <%= f.label :comment , class: "form-control-label"%>
                    <%= f.text_area :comment, class: "form-control", value: comment.comment, size: "40x10" %>
                    <%= f.submit "編集", class: "btn"%>
                  <% end%>
                  <button class="close_modal">閉じる</button>
                </div>
                <div class="content_delete_buttom">
                  <%= link_to comment, method: :delete do %>
                    <button>削除</button>
                  <%end%>
                </div>
              </div>
            <% end%>
          <% end%>
        <% else %>
          <p>コメントはありません！</p>
        <% end %>
      </section>
      <section class="input_comment_area">
        <%= form_with model: Comment.new do |f| %>
          <%= render 'layouts/error_form', model: @new_comments %>
          <p>名前</p>
          <%= f.text_field :name %>
          <p>コメント</p>
          <%= f.text_area :comment, size: "90x10" %>
          <%= f.hidden_field :post_id, value: @post.id %><br>
          <%= f.submit "投稿", class: "bottom_area", class: "btn" %>
        <% end %>
      </section>
    </section>
    <section class="sidebar_area">
      <% if logged_in? && current_user?(@post.user_id) %>
        <div class="btn_area">
          <div class="content_edit_buttom">
            <%= link_to "編集", edit_post_path(@post), class: "btn", method: :get %>
          </div>
          <div class="content_delete_buttom">
            <%= link_to "削除", post_path(@post), class: "btn", method: :delete %>
          </div>
        </div>
      <% end %>
      <% if @post.user_id? %> 
        <div class="profile_thumbnail_area">
          <% if @post.user_id? && @post.user.user_image.attached? %> 
            <%= image_tag @post.user.user_image, size: '300x300', class: "profile_thumbnail" %> 
          <% else %> 
            <%= image_tag "/no_image.png", class: "thumbnail_image" %>
          <% end%>
        </div>
        <div class="name_area">
          <%= @post.user.name %>
        </div>
        <% if @post.user.profile %> 
          <div class="profile_area">
            <%= @post.user.profile %>
          </div>
        <% end%>
        <% if @post.user.birthday %> 
          <div class="birthday_area">
            <%= l @post.user.birthday, format: :long %>
          </div>
        <% end%>
      <% end%>
    </section>
  </div>
</article>

app/views/setting/show.html.erb
<article>
  <div class="container">
    <section class="main_area">
      <div class="input_area">
        <h1>Profile</h1>
        <%= form_with model: @user, url: setting_path do |f| %>
          <p>プロフィール</p>
          <%= f.text_area :profile, size: "136x10", value: @user.profile%>
          <p>誕生日</p>
          <% if @user.birthday %> 
            <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: @user.birthday%>
          <% else %>
            <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1)%>
          <% end%>
          <p>プロフィール画像</p>
          <% if @user.user_image.attached? %> 
            <%= image_tag @user.user_image, size: '300x300', class: "thumbnail_image" %><br>
          <% else %> 
            <%= image_tag "/no_image.png", class: "thumbnail_image" %>
          <% end%>
          <label for="thumbnail_image" class="square_btn">
          プロフィール画像選択
          <%= f.file_field :user_image, :class => "ignore" %>
          </label>
          <div class="btn_area">
            <%= f.submit "登録", class: "btn" %>
            <%= link_to "退会", show_withdraw_path(@user.id), class: "btn", method: :get %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</article>

app/views/setting/user/show.html.erb
<article>
  <div class="container">
    <section class="main_area">
      <div class="input_area">
        <h1>Profile</h1>
        <%= form_with model: @user, url: setting_user_path do |f| %>
          <p>ブログネーム</p>
          <%= f.text_field :blog_name, size: "136x10", value: @user.blog_name%>
          <p>プロフィール</p>
          <%= f.text_area :profile, size: "136x10", value: @user.profile%>
          <p>誕生日</p>
          <% if @user.birthday %> 
            <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: @user.birthday%>
          <% else %>
            <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1)%>
          <% end%>
          <p>プロフィール画像</p>
          <% if @user.user_image.attached? %> 
            <%= image_tag @user.user_image, size: '300x300', class: "thumbnail_image" %><br>
          <% else %> 
            <%= image_tag "/no_image.png", class: "thumbnail_image" %>
          <% end%>
          <label for="thumbnail_image" class="square_btn">
          プロフィール画像選択
          <%= f.file_field :user_image, class: "ignore" %>
          </label>
          <div class="btn_area">
            <%= f.submit "登録", class: "btn" %>
            <%= link_to "退会", show_withdraw_path(@user.id), class: "btn", method: :get %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</article>