config/routes.rb
Rails.application.routes.draw do
  get                '/',    to: 'home#index', as: :root
  resources :signup, only: [:new, :create]
  get            'login',    to: 'sessions#new'
  post           'login',    to: 'sessions#create'
  delete        'logout',    to: 'sessions#delete'
  resources :posts, expect: [:index]
  resources :comments, only: [:show, :create, :update, :destroy]
  namespace :mypage do
    resources :user, only: [:show]
  end
  namespace :setting do 
    resources :user, only: [:show, :update]
  end
  get     'withdraw/:id',    to: 'withdraw#show', as: :show_withdraw
  delete  'withdraw/:id',    to: 'withdraw#delete', as: :delete_withdraw
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
  validates :name, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  
  has_many :comments, dependent: :destroy
  has_one_attached :post_image

  validates :title, presence: true
  validates :article, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :posts, dependent: :destroy
  has_one_attached :user_image

  validates :name, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password_digest, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_confirmation, only:[:update, :destroy]

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:comment][:post_id])
    new_comments = @post.comments.build(comment_params)
    if new_comments.save
      redirect_back(fallback_location: root_path, notice: '投稿に成功しました。')
    else
      render 'posts/show', alert: '編集に失敗しました。'
    end
  end

  def update
    comment = Comment.find(params[:id])
    if comment.update_attributes(comment_params)
      redirect_back(fallback_location: root_path, notice: '編集に成功しました。')
    else
      redirect_back(fallback_location: root_path, alert: '編集に失敗しました。')
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_back(fallback_location: root_path, notice: '削除に成功しました。')
    else
      redirect_back(fallback_location: root_path, alert: '削除に失敗しました。')
    end
  end

private
  def comment_params
    params.require(:comment).permit(:name, :comment)
  end

  def user_confirmation
    @comment = Comment.find(params[:id])
    unless current_user.id == @comment.post.user_id
      flash[:alert] = "コメント編集は記事の投稿者のみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_confirmation, only: [:edit, :update, :destroy]

  def new 
    @post = Post.new
  end

  def create
    current_user.present? ? @post = current_user.posts.build(post_params) : @post = Post.new(post_params)
    if @post.save
      flash[:notice] = '投稿に成功しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '投稿に失敗しました。'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = '更新に成功しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '更新に失敗しました。'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy!
      flash[:notice] = '削除しました。'
      redirect_to controller: :home, action: :index
    else
      flash[:alert] = '削除に失敗しました。'
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :article, :post_image)
  end

  def user_confirmation
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      flash[:alert] = "記事編集は投稿者のみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password]) && withdraw_user(user)
      log_in user
      redirect_to "/mypage/user/#{user.id}"
    else
      flash[:alert] = '正しいメールアドレス、パスワードを入力してください。'
      redirect_back(fallback_location: root_path)
    end
  end

  def delete
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/setting_controller.rb
require'date'

class SettingController < ApplicationController
  include Common

  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    @user.birthday = birthday_join
    if @user.save
      redirect_back(fallback_location: root_path, notice: '編集に成功しました。')
    else
      render controller: :setting, action: :show, alert: '編集に失敗しました。'
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile, :birthday, :user_image)
  end

  def birthday_join
    date = params[:user]
    Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to "/mypage/user/#{@user.id}"
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:name, :blog_name, :email, :password, :password_confirmation)
  end
end

app/controllers/withdraw_controller.rb
class WithdrawController < ApplicationController
  before_action :user_confirmation, only: [:delete]

  def show
    @user = User.find(params[:id])
  end

  def delete
    @user = User.find(params[:id])
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
    flash[:notice] = '退会に成功しました。'
  end

  private
  def user_confirmation
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:alert] = "退会は登録ユーザーのみです。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user.id
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def withdraw_user(user)
    user.is_active
  end
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <div class="alert alert-info">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% elsif alert %>
  <div class="alert alert-danger">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/layouts/_error_form.html.erb
<% if model.present? and model.errors.any? %>
  <div class = "alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_posts.html.erb
<div class="content_area">
  <% posts.each do |post| %>
    <div class="content_info">
      <%= link_to post_path :id => post.id do %>
        <div class="thumbnail_area">
          <% if post.post_image.attached? %> 
            <%= image_tag post.post_image, size: '300x300', class: "thumbnail_image" %> 
          <% else %> 
            <%= image_tag "/no_image.png", class: "thumbnail_image" %>
          <% end%>
        </div>
      <% end %>
      <div class="info_area">
        <h2>タイトル:
          <%= link_to post_path id: post.id do %>
            <%= post.title %>
          <% end %>
        </h2>
        <p>日付:<%= l post.created_at, format: :long %></p>
        <% if post.user_id? %> 
          <p>作者:
            <%= link_to mypage_user_path id: post.user.id do %>
              <%= post.user.name %>
            <% end %>
          </p>
        <% end %>
        <p>コメント数:<%= post.comments.length%></p>
      </div>
    </div>
  <% end %>
  <%= paginate posts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ハレブロ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller] %>
    <script src="https://kit.fontawesome.com/a93df4ec79.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <div class="header_area">
        <div class="left_area">
          <%= link_to "ハレブロ", root_path %>
        </div>
        <div class="right_area">
          <% if logged_in? %>
            <%= link_to "マイページ", mypage_user_path(current_user.id) %>
            <%= link_to "セッティング", setting_user_path(current_user.id) %>
            <%= link_to "ログアウト", logout_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", login_path %>
            <%= link_to "会員登録", new_signup_path %>
          <% end %>
        </div>
      </div>
    </header>
    <%= render 'layouts/alert' %>
    <%= yield %>
    <footer>
      <div class="footer_area">
        <div class="center">
          <p>&copy;Copyright 2020</p>
          <%= link_to "ハレブロ", root_path %>
        </div>
      </div>
    </footer>
  </body>
</html>